# Generated by Django 5.2.4 on 2025-07-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(0, 'World'), (1, 'U.S'), (2, 'Technology'), (3, 'Desing'), (4, 'Culture'), (5, 'Business')], default=0, help_text='Categoría del post', max_length=20),
        ),
    ]
