# Generated by Django 5.2.4 on 2025-07-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('World', 'World'), ('U.S', 'U.S'), ('Technology', 'Technology'), ('Desing', 'Desing'), ('Culture', 'Culture'), ('Business', 'Business')], default='World', help_text='Categoría del post', max_length=20),
        ),
    ]
